steps:
  - id: build-api-python
    name: gcr.io/cloud-builders/docker
    dir: api-python
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/api-python:${_TAG}
      - .

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/api-python:${_TAG}

substitutions:
  _REGION: asia-south1
  _REPO: ragify
  _TAG: latest
