services:
  # api:
  #   container_name: ragify-api
  #   build: ./api/Dockerfile
  #   env_file:
  #     - ./api/.env
  #   ports:
  #     - "1337:${PORT}"
  #   environment:
  #     - MONGODB_URI: ${MONGODB_URI}
  #   depends_on:
  #     - database
  #   restart: unless-stopped

  # web:
  #   container_name: ragify-web
  #   build: ./web/Dockerfile
  #   ports:
  #     - "5137:5137"
  #   environment:
  #     - VITE_API_URL=http://localhost:1337
  #   restart: unless-stopped

  db:
    container_name: ragify-db
    image: mongo:8.2.3
    restart: unless-stopped
    env_file:
      - ./api/.env
    volumes:
      - ${MONGO_DATA_PATH:-./api/mongo_data_volume}:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-myuser}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-mypassword}
    ports:
      - "27017:27017"

  vector_db:
    image: qdrant/qdrant:latest
    container_name: ragify_qdrant
    restart: unless-stopped
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # gRPC
    volumes:
      - ./qdrant_db:/qdrant/storage

volumes:
  data:
