import { Component } from '@angular/core';
import { LegalPageComponent } from './legal-page.component';

@Component({
  standalone: true,

  selector: 'app-terms-page',
  imports: [LegalPageComponent],
  template: `
    <app-legal-page
      title="Terms of service"
      meta="Effective date: August 18, 2026"
      footer="Ragify terms of service v1.0"
      icon="FileText"
    >
      <section class="space-y-3">
        <h2 class="text-lg font-semibold tracking-tight">1. The service</h2>
        <p class="text-sm leading-relaxed text-muted-foreground">
          Ragify provides hosted workspaces that index your documents and answer questions with source citations.
          By creating an account or using the service, you agree to these terms.
        </p>
      </section>

      <section class="space-y-3">
        <h2 class="text-lg font-semibold tracking-tight">2. Accounts and acceptable use</h2>
        <div class="space-y-2 border border-border bg-muted/20 p-4">
          <p class="text-sm font-semibold text-foreground">You agree to:</p>
          <p class="text-sm leading-relaxed text-muted-foreground">
            Keep your credentials secure, upload only content you have the right to index, and not use the service
            to store or generate unlawful material. We may suspend accounts that violate these terms.
          </p>
        </div>
      </section>

      <section class="space-y-3">
        <h2 class="text-lg font-semibold tracking-tight">3. Plans and billing</h2>
        <ul class="list-disc space-y-3 pl-5 text-sm leading-relaxed text-muted-foreground">
          <li>The Free plan is available without a credit card and may be used subject to published limits.</li>
          <li>Paid plans are billed in advance on a monthly basis and can be cancelled at any time.</li>
          <li>Features, limits, and pricing are described on the pricing page and may change with notice.</li>
        </ul>
      </section>

      <section class="space-y-3">
        <h2 class="text-lg font-semibold tracking-tight">4. Intellectual property</h2>
        <p class="text-sm leading-relaxed text-muted-foreground italic">
          You retain ownership of the documents you upload. Ragify grants you a limited license to use the service
          for its intended purpose, and you may not resell or reverse-engineer it without permission.
        </p>
      </section>

      <section class="space-y-3">
        <h2 class="text-lg font-semibold tracking-tight">5. Availability and liability</h2>
        <p class="text-sm leading-relaxed text-muted-foreground">
          The service is provided "as is" without warranties of any kind. Ragify is not liable for indirect or
          consequential damages, and our total liability is limited to the amount you paid in the three months
          before the claim. Answers generated by the service are informational and should be verified against your
          sources.
        </p>
      </section>
    </app-legal-page>
  `,
})
export class TermsPageComponent {}
